FROM node:24-alpine3.21

WORKDIR /app

# Copiamos solo los manifiestos primero
COPY ../package*.json ./

# Instalamos dependencias
RUN npm install

# Copiamos todo el código fuente
COPY ../ ./

# Ejecutamos build
RUN npm run build