# Etapa de build
FROM node:24-alpine3.21 AS builder

WORKDIR /app

# Copiamos solo los manifiestos primero
COPY ../package*.json ./

# Instalamos dependencias
RUN npm install

# Copiamos todo el código fuente
COPY ../ ./

# Ejecutamos build
RUN npm run build

FROM node:24-alpine3.21 AS runner

WORKDIR /app

# Instalamos 'serve' globalmente para servir los archivos estáticos
RUN npm install -g serve

# Copiamos el build
COPY --from=builder /app/dist ./dist

# Arranque
CMD ["serve", "-s", "dist", "-l", "5173"]
